### ISSUE TITLE
Is turn turning the right direction?

### ISSUE THREAD

**Issue by fgrossman** [Open-STEM/XRP_MicroPython#29]
I would expect a turn 90 to turn 90 degrees clockwise.

**Comment by Kreeevin** [comment]
From my perspective (and from that of the IMU), a positive angle is represented by a counterclockwise motion. I can change this if you want, but I think it makes more sense from an educational prospective, since positive being counterclockwise is consistent with physics, polar coordinates, and other places rotations are taught

**Comment by fgrossman** [comment]
Brad is going to investigate this. I think we should do the same thing as FRC & FTC does. And more people are probably educated in compass directions than IMU mems devices physics.
