### ISSUE TITLE
Encoded_motor ticks only work with set_speed

### ISSUE THREAD

**Issue by fgrossman** [Open-STEM/XRP_MicroPython#37]
The code below gives a tick count of zero.  If I use set_speed the tick count advances

```
from XRPLib.encoded_motor import EncodedMotor
import time

motor1 = EncodedMotor.get_default_encoded_motor(1)


motor1.set_effort(0.8)
time.sleep(2)
motor1.set_effort(0)
print(motor1.get_position_ticks())
```

**Comment by Kreeevin** [comment]
![image](https://github.com/Open-STEM/XRP_MicroPython/assets/67293695/3a199c14-06df-4aaf-ad3c-42c3ff266cd7)
I don't love this answer but I think this is caused by the same thing as #31. After 3-4 prints, it then actually updates to the next jump in values. 
![image](https://github.com/Open-STEM/XRP_MicroPython/assets/67293695/53f0e545-160b-4d20-b086-4ccbcb57a11b)

**Comment by Kreeevin** [comment]
![image](https://github.com/Open-STEM/XRP_MicroPython/assets/67293695/1cce88d9-5016-441c-b627-59929119b52b)
extra screenshot to show minimal reproduction steps

**Comment by Kreeevin** [comment]
see comment on #31, solved for now.
